SELECT * FROM EMPLOYEES WHERE UCASE(FIRST_NAME)='KELLIE' AND GENDER='F';

SELECT * FROM EMPLOYEES WHERE UCASE(FIRST_NAME)='KELLIE' OR UCASE(FIRST_NAME)='ARUNA';

SELECT * FROM EMPLOYEES WHERE GENDER='F' AND (UCASE(FIRST_NAME)='KELLIE' OR UCASE(FIRST_NAME)='ARUNA');

SELECT * FROM EMPLOYEES WHERE UCASE(FIRST_NAME) IN ('DENIS','ELVIS');

SELECT * FROM EMPLOYEES WHERE UCASE(FIRST_NAME) NOT IN ('JOHN','MARK','JACOB');

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE('MARK%');

SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE('%2000%');

SELECT * FROM EMPLOYEES WHERE EMP_NO LIKE ('1000_');

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE ('%JACK%');

SELECT * FROM EMPLOYEES WHERE FIRST_NAME NOT LIKE ('%JACK%');

SELECT * FROM SALARIES WHERE SALARY BETWEEN 66000 AND 70000;

SELECT * FROM EMPLOYEES WHERE EMP_NO NOT BETWEEN 10004 AND 10012;

SELECT * FROM DEPARTMENTS WHERE DEPT_NO BETWEEN 'D003' AND 'D006';

select * from employees where hire_date > '2000-01-01' and gender='f';

select salary from salaries where salary > 150000;

select distinct hire_date from employees;